// <auto-generated />
using System;
using IshikawaRca.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IshikawaRca.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RcaDbContext))]
    [Migration("20260603201406_AddRcaEvidenceValidationMetadata")]
    partial class AddRcaEvidenceValidationMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IshikawaRca.Domain.Entities.CorrectiveAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid?>("CauseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RcaIncidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TenantId"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ValidationNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("RcaIncidentId");

                    b.HasIndex("TenantId", "CauseId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "RcaIncidentId");

                    b.HasIndex("TenantId", "Status", "DueDate");

                    b.ToTable("corrective_actions", (string)null);
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.IshikawaBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RcaIncidentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TenantId"), "ascii");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("RcaIncidentId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "RcaIncidentId", "Order");

                    b.ToTable("ishikawa_branches", (string)null);
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.IshikawaCause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("FrequencyScore")
                        .HasColumnType("int");

                    b.Property<int>("ImpactScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRootCause")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ParentCauseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProbabilityScore")
                        .HasColumnType("int");

                    b.Property<Guid>("RcaIncidentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TenantId"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<decimal>("X")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Y")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "IsRootCause");

                    b.HasIndex("TenantId", "ParentCauseId");

                    b.HasIndex("TenantId", "RcaIncidentId");

                    b.ToTable("ishikawa_causes", (string)null);
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.RcaEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<string>("AttachmentContentType")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("AttachmentFileName")
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("AttachmentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("AttachmentSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("AttachmentStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AttachmentStorageProvider")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CapturedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid?>("CauseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("ExternalIntakeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RcaIncidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceUri")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TenantId"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValidatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ValidationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("RcaIncidentId");

                    b.HasIndex("TenantId", "CauseId");

                    b.HasIndex("TenantId", "ExternalIntakeId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "ValidationStatus");

                    b.HasIndex("TenantId", "RcaIncidentId", "CapturedAt");

                    b.ToTable("rca_evidence", (string)null);
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.RcaExternalIntakeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<string>("ActorName")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BatchOrLot")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ClaimReference")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ContainmentResponse")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaterialCode")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProposedCorrectiveAction")
                        .HasColumnType("text");

                    b.Property<string>("ProposedRootCause")
                        .HasColumnType("text");

                    b.Property<Guid>("RcaIncidentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RejectedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TenantId"), "ascii");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "ActorType", "ActorName");

                    b.HasIndex("TenantId", "RcaIncidentId", "Status");

                    b.ToTable("rca_external_intake_requests", (string)null);
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.RcaIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<string>("ClaimActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ClaimOwnerName")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ClaimScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClosedByUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("ClosureSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ContextSnapshotJson")
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<bool>("EscalatedTo8D")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("EscalatedTo8DAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EscalatedTo8DByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ExternalWorkOrderId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LineCode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TaskSnapshotJson")
                        .HasColumnType("json");

                    b.Property<Guid>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TenantId"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("WizardStep")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("WizardStepCompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WizardStepCompletedByUserId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("WizardStepNotes")
                        .HasColumnType("text");

                    b.Property<string>("WorkOrderCode")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.HasIndex("TenantId", "ClaimActorType", "ClaimOwnerName");

                    b.HasIndex("TenantId", "ClaimScope", "ClaimOwnerName");

                    b.HasIndex("TenantId", "MachineCode", "OccurredAt");

                    b.HasIndex("TenantId", "SourceSystem", "ExternalTaskId");

                    b.HasIndex("TenantId", "Status", "Severity");

                    b.ToTable("rca_incidents", (string)null);
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.CorrectiveAction", b =>
                {
                    b.HasOne("IshikawaRca.Domain.Entities.RcaIncident", null)
                        .WithMany("CorrectiveActions")
                        .HasForeignKey("RcaIncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.IshikawaBranch", b =>
                {
                    b.HasOne("IshikawaRca.Domain.Entities.RcaIncident", null)
                        .WithMany("Branches")
                        .HasForeignKey("RcaIncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.IshikawaCause", b =>
                {
                    b.HasOne("IshikawaRca.Domain.Entities.IshikawaBranch", null)
                        .WithMany("Causes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.RcaEvidence", b =>
                {
                    b.HasOne("IshikawaRca.Domain.Entities.RcaIncident", null)
                        .WithMany("Evidence")
                        .HasForeignKey("RcaIncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.IshikawaBranch", b =>
                {
                    b.Navigation("Causes");
                });

            modelBuilder.Entity("IshikawaRca.Domain.Entities.RcaIncident", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("CorrectiveActions");

                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
